datamodule:
  paths:
    preprocess_dir: /data/users/user6/rxh/datasets/casme^2/74.220.215.205/prerpocess   # win*.npz 根目录

  seed: 42

  split:
    mode: random          # ['LOSO' | 'random']
    test_subject: s16

  loader:
    batch_size : 4
    num_workers: 0