defaults:
  - _self_
  - paths
preprocess:
  window_size: 128
  stride: 64

  flow:
    w1: 0.7
    w2: 0.3
    method: tvl1

  dhg:
    base: 0.1
    peak: 1.0

  pseudo_apex:
    use_if_overlap_half: True

  neg_sample_ratio: 2

  num_workers: 4

  input_dir: ${paths.raw_data_dir}
  flow_curve_dir: ${paths.flow_curve_dir}
  output_dir: ${paths.preprocess_dir}
  anno_file: ${paths.anno_file}

  seed: 42