defaults:
  - preprocess
  - _self_

paths:
  preprocess_dir: /data/users/user6/rxh/datasets/casme^2/74.220.215.205/prerpocess
  input_dir: /data/users/user6/rxh/datasets/casme^2/74.220.215.205/Cropped224_all

model:
  name: OpenGVLab/VideoMAEv2-Base